insert into fabricantes (id, nombre) values (1, 'Dianne');
insert into fabricantes (id, nombre) values (2, 'Ellary');
insert into fabricantes (id, nombre) values (3, 'Idette');
insert into fabricantes (id, nombre) values (4, 'Briana');
insert into fabricantes (id, nombre) values (5, 'Jorie');
insert into fabricantes (id, nombre) values (6, 'Dode');
insert into fabricantes (id, nombre) values (7, 'Rhea');
insert into fabricantes (id, nombre) values (8, 'Karilynn');
insert into fabricantes (id, nombre) values (9, 'Tiertza');
insert into fabricantes (id, nombre) values (10, 'Clayson');

insert into productos (id, nombre, precio, fabricante_id) values (1, 'Jillie', 96, 1);
insert into productos (id, nombre, precio, fabricante_id) values (2, 'Mar', 58, 1);
insert into productos (id, nombre, precio, fabricante_id) values (3, 'Broderic', 60, 2);
insert into productos (id, nombre, precio, fabricante_id) values (4, 'Carlina', 87, 2);
insert into productos (id, nombre, precio, fabricante_id) values (5, 'Robby', 36, 3);
insert into productos (id, nombre, precio, fabricante_id) values (6, 'Lynda', 16, 3);
insert into productos (id, nombre, precio, fabricante_id) values (7, 'Ianthe', 4, 4);
insert into productos (id, nombre, precio, fabricante_id) values (8, 'Margeaux', 57, 4);
insert into productos (id, nombre, precio, fabricante_id) values (9, 'Stormie', 44, 5);
insert into productos (id, nombre, precio, fabricante_id) values (10, 'Gerick', 85, 5);
insert into productos (id, nombre, precio, fabricante_id) values (11, 'Noam', 48, 6);
insert into productos (id, nombre, precio, fabricante_id) values (12, 'Truda', 98, 6);
insert into productos (id, nombre, precio, fabricante_id) values (13, 'Ernesta', 39, 7);
insert into productos (id, nombre, precio, fabricante_id) values (14, 'Hilary', 99, 7);
insert into productos (id, nombre, precio, fabricante_id) values (15, 'Halsey', 92, 8);
insert into productos (id, nombre, precio, fabricante_id) values (16, 'Elise', 84, 8);
insert into productos (id, nombre, precio, fabricante_id) values (17, 'Edsel', 92, 9);
insert into productos (id, nombre, precio, fabricante_id) values (18, 'Hailey', 81, 6);
insert into productos (id, nombre, precio, fabricante_id) values (19, 'Tory', 7, 7);
insert into productos (id, nombre, precio, fabricante_id) values (20, 'Tremaine', 40, 10);
